apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
  labels:
    app: threat-api
    tier: backend
spec:
  
  replicas: 3
  
  selector:
    matchLabels:
      app: threat-api
  template:
    metadata:
      labels:
        app: threat-api
    spec:
        containers:
        - name: api
          image: taktuk/threat-api:v1
          ports:
          - containerPort: 8000
            name: http 
        env:
        - name: MONGO_HOST
          value: mongo-0.mongo
        - name: MONGO_PORT
          value: 27017
        - name: MONGO_USERNAME
          value: admin
        - name: MONGO_PASSWORD
          value: sectetpass
        - name: MONGO-DB
          value: threat-db
        - name: ONGO_AUTH_SOURCE
          value: admin
